g2: officially added Linux path (with just Firefox though)

diff --git a/bin/g2 b/bin/g2
--- a/bin/g2
+++ b/bin/g2
@@ -18,17 +18,29 @@ user_conf="$tooldir/../conf/g2-user.conf"
 
 ## list of browsers + full path
 case "$(uname)" in 
+  ## Mac OSX
   Darwin)
    [[ -z $chrome_bin  ]] && chrome_bin='/Applications/Google Chrome.app'
    [[ -z $firefox_bin ]] && firefox_bin='/Applications/Firefox.app'
    [[ -z $default2use ]] && default2use=$chrome_bin
   ;;
-  *)
+  
+  Linux)
+   [[ -z $firefox_bin ]] && firefox_bin='/usr/bin/firefox'
+   [[ -z $default2use ]] && default2use=$firefox_bin
+  ;;
+
+  CYGWIN*)
    [[ -z $chrome_bin  ]] && chrome_bin='/cygdrive/c/Program Files (x86)/Google/Chrome/Application/chrome.exe'
    [[ -z $firefox_bin ]] && firefox_bin='/cygdrive/c/Program Files (x86)/Mozilla Firefox/firefox.exe'
    [[ -z $ie_bin      ]] && ie_bin='/cygdrive/c/Program Files/Internet Explorer/iexplore.exe'
    [[ -z $iron_bin    ]] && iron_bin='/cygdrive/c/Program Files (x86)/SRWare Iron/iron.exe'
    [[ -z $default2use ]] && default2use=$iron_bin
+  ;;
+
+  *)
+   echo "ERROR: Unknown platform. Supported are Mac/Linux/Cygwin"
+   exit 1
   ;;
 esac
 
